### ISSUE TITLE
Concerns about Filipino Translations

### ISSUE THREAD

**Issue by codygee237** [woothemes/sensei-language-packs#1]
Hi Good Day Sir!

How can I translate the file fil_PH? Do I need to add a new file for fil_PH or just translate it on the existing file? I'm hoping for your quick response Sir.

Best Regards,
codygee237

**Comment by donnapep** [comment]
You can find documentation for adding a translation to Sensei [here](https://docs.woocommerce.com/document/localising-sensei/). Thx!
